### ISSUE TITLE
Clean Up Root Directory

### ISSUE THREAD

**Issue by JCapriotti** [bots-edi/bots-tmp#6]
I have OCD.

The root of the bots repo has way too much stuff in there. My initial thought is to create a subdirectory like /scripts to dump most of the build and execution scripts. I don't want to do that blindly though, so might have to take some time to test that. I haven't done much with running the build scripts lately, and for now it seems like scripts should remain working as they are.

**Comment by WouterVH** [comment]
it bothers me as well, i will work on this.

**Comment by WouterVH** [comment]
move unittests to tests-subdir: done
move scripts to scripts-subdir: done

**Comment by WouterVH** [comment]
I want to completely remove all setup_*.py files.
To install ion windows virtualenv or miniconda are the way to go, an not generatin bdist_win eggs.

**Comment by JCapriotti** [comment]
I like the moves so far. But I'm curious... the .py files in scripts loads modules that are moved to the src/bots directory (up one level and then down into bots). I'm used to just running `python bots-engine.py`, so now it can't find the module. 

Maybe those scripts like bots-engine.py should be in src?

I'm sure I can figure out a good change, but I don't know what is typical for structure, so thought I'd ask.

**Comment by WouterVH** [comment]
we have a "script" in /scripts/bots-engine.py.
it is a script because it is listed as a script in setup.py. it becomes something more special.

this means that this script gets installed in the executable directory of your python-env when you install the bots-module. for a virtualenv, the script is then bin/bots-engine.py.

>>Maybe those scripts like bots-engine.py should be in src?
regardless of location, the executable that you needs to use, ends up in the bin-directory.

python packages could be installed as a zipped file, then you cannot use it the way you try now.

however such scripts still are old-style,
and entrypoints are better and newer, we create them directly on setup.py , and they do not need a wrapperscript like oldstyle script.
entrypoints are also created in the bin-dir, but withouth .py-extension.

**Comment by JCapriotti** [comment]
That makes sense. I'm still learning Python from a distribution perspective. 

I asked because I'm running bots-engine from source (i.e. for testing the code, not from a pip install). I'm not sure the best way to do this. What I thought would work is running this from the src directory: 

    python -c "from bots import engine; engine.start()"

This line in botsglobal.py causing a problem:

    version = pkg_resources.get_distribution('bots').version

Is there a sort of debug conditional that should go around this line? Here's the error...

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "bots/engine.py", line 17, in <module>
    from . import botslib
  File "bots/botslib.py", line 26, in <module>
    from . import botsglobal
  File "bots/botsglobal.py", line 7, in <module>
    version = pkg_resources.get_distribution('bots').version  # bots version
  File "/home/jason/git/bots/.env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 535, in get_distribution
    dist = get_provider(dist)
  File "/home/jason/git/bots/.env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 415, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/jason/git/bots/.env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jason/git/bots/.env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'bots' distribution was not found and is required by the application
```

**Comment by JCapriotti** [comment]
Figured out how this is supposed to work.

Running `pip install -e .` in the root seems to be the thing I was missing.

**Comment by WouterVH** [comment]
yes, the bots-package was not yet installed in your case.

installing in develop-mode is indeed correct:
> pip install -e .

**Comment by WKaz** [comment]
This fork is inactive. We've moved the development to https://gitlab.com/bots-ediint/. More information about the project is gathered here: https://bots-edi.org/.
